# Generated by Django 4.2.4 on 2023-08-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('su', 'Supplier'), ('st', 'Stuff'), ('de', 'Delivery'), ('cu', 'Customer')], max_length=10),
        ),
    ]
